### ISSUE TITLE
Branch fails

### ISSUE THREAD

**Issue by chmac** [GenerousLabs/git-remote-encrypted#12]
There are a few scenarios that cause issues with branches.

The `.git/encrypted` repo assumes a branch name of `master`. In recent git versions, this is configurable. We need to handle this better.

The git-encrypted-host-git-api package runs `git pull` and `git push`, but if you have weird branch config settings (or maybe settings added in recent git versions) then things go awry. Let's add specific branches to the pull and push commands.

**Comment by johannes87** [comment]
When the global .gitconfig has the following setting, git push fails:

```
[push]
        default = matching
```

Error:
```
$ git push -u enc master                                                                                                          master ✔
GitRemoteHelper ERROR #W9flRj
Error: External git pull failed #O2TOzC
    at _callee3$ (/Users/johannes/coding/GenerousLabs/johannes87/git-remote-encrypted/packages/git-remote-encrypted/cli/index.js:42562:19)
    at tryCatch (/Users/johannes/coding/GenerousLabs/johannes87/git-remote-encrypted/packages/git-remote-encrypted/cli/index.js:41767:19)
    at Generator.invoke [as _invoke] (/Users/johannes/coding/GenerousLabs/johannes87/git-remote-encrypted/packages/git-remote-encrypted/cli/index.js:41984:24)
    at Generator.next (/Users/johannes/coding/GenerousLabs/johannes87/git-remote-encrypted/packages/git-remote-encrypted/cli/index.js:41820:23)
    at asyncGeneratorStep (/Users/johannes/coding/GenerousLabs/johannes87/git-remote-encrypted/packages/git-remote-encrypted/cli/index.js:41666:24)
    at _next (/Users/johannes/coding/GenerousLabs/johannes87/git-remote-encrypted/packages/git-remote-encrypted/cli/index.js:41688:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
